/*
 * dataflash_board_config.h
 *
 * Created: 21-4-2013 12:13:10
 *  Author: Vito
 */ 


#ifndef DATAFLASH_BOARD_CONFIG_H_
#define DATAFLASH_BOARD_CONFIG_H_

#define LEDPORT		PORTA	
#define LED_GREEN	PIN3_bm
#define LED_ORANGE	PIN4_bm
#define BC_SET_LEDS()	(LEDPORT.DIRSET = LED_GREEN | LED_ORANGE)

#define SWITCHPORT	PORTB
#define SWITCH_ONE	PIN6_bm
#define SWITCH_TWO	PIN5_bm
#define BC_SWITCH_PULLDOWN() {\
	SWITCHPORT.PIN6CTRL |= PORT_OPC_PULLDOWN_gc;\
	SWITCHPORT.PIN5CTRL |= PORT_OPC_PULLDOWN_gc;\
}

#define BC_RISING_INT_SW1(){\
	SWITCHPORT.INT0MASK |= SWITCH_ONE;\
	SWITCHPORT.PIN6CTRL |= PORT_ISC_RISING_gc;\
	SWITCHPORT.INTCTRL  |= PORT_INT0LVL_MED_gc;\
}

#define BC_RISING_INT_SW2(){\
	SWITCHPORT.INT0MASK |= SWITCH_TWO;\
	SWITCHPORT.PIN5CTRL |= PORT_ISC_RISING_gc;\
	SWITCHPORT.INTCTRL  |= PORT_INT0LVL_MED_gc;\
}		

#define UNDERVPORT	PORTB
#define UNDERV_PIN	PIN2_bm




#endif /* DATAFLASH_BOARD_CONFIG_H_ */